export const mapping = {
  "Abmessungen": "dimensions",
  "Abstract": "description",
  "Artist": "creator",
  "Associated Person(s)": "contributor",
  "Author": "creator",
  "Author(s)": "creator",
  "Author(s) of the Record": "member.role.documentedBy",
  "Beschreibstoff" : "encoding",
  "Birthplace": "birthPlace",
  "Call number": "identifer.shelfmark",
  "Classification": "additionalType",
  "Classmark": "identifier.shelfmark",
  "Collection": "isPartOf",
  "Collection Name": "isPartOf",
  "Credit Line": "funder",
  "Culture & Date": "dateCreated",
  "Date": "datePublished",
  "datiert": "datePublished",
  "Datierung": "datePublished",
  "Date of Creation": "dateCreated",
  "Date of Origin (English)": "dateCreated",
  "Date of publication": "datePublished",
  "Date of Publication": "datePublished",
  "description": "description",
  "Description": "description",
  "Dimensions": "disambiguatingDescription",
  "Document Type": "additionalType",
  "DOI": "identifier.doi",
  "Extent": "disambiguatingDescription",
  "Format": "material.format",
  "Former Owner(s)": "acquiredFrom",
  "@id": "url",
  "id": "url",
  "identifier": "identifier",
  "Inscription": "text.inscription",
  "Language(s)": "inLanguage",
  "Language": "inLanguage",
  "Lokalisierung": "location",
  "Location": "location",
  "manifest": "url",
  "Manifest": "url",
  "Manuscripta Mediaevalia" : "sameAs",
  "Markings": "text.markings",
  "Material": "material",
  "Medium": "material",
  "Number of Pages": "numberOfPages",
  "Objekttitel": "alternateName",
  "Object Number": "identifier.object",
  "Origin Place": "location.origin",
  "Part reference": "isPartOf",
  "People": "creator",
  "Persons": "creator",
  "Physical Location": "location.owner",
  "Physical State": "numberOfPages",
  "Place" : "location",
  "Place Created": "location.created",
  "Place Depicted": "location.depicted",
  "Place Found": "location.found",
  "Place of Origin (English)": "location.origin",
  "Place of publication": "location.publication",
  "Place of Publication": "location.publication",
  "Provenance": "citation",
  "Publisher" : "publisher",
  "Recipient": "member.role.receivedBy",
  "related": "sameAs",
  "seeAlso": "seeAlso",
  "Scribes": "member.role.scribe",
  "Shelfmark": "identifier.shelfmark",
  "Signatur": "identifier.shelfmark",
  "Signed": "text.signature",
  "Sprache": "inLanguage",
  "Source Images": "sameAs",
  "subCollection": "subCollection",
  "Subject(s)": "additionalType",
  "Summary (English)": "description",
  "Technique": "genre",
  "Text Language": "inLanguage",
  "Title": "name",
  "Titel (aus Signatur)": "name",
  "Title (English)": "name",
  "title": "alternateName",
  "Type": "additionalType",
  "Umfang": "numberOfPages",
  "URN" : "identifier.urn"
}

